import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireDebugAccess } from "@/lib/debug-auth";
import { pushAriForDateRange } from "@/lib/channels/channex-ari";
import { ChannexError } from "@/lib/channels/channex-core";

// Triggers a full ARI resync for one Channex-managed property: certification
// test 1, "Full Data Update (Full Sync)".
//
// Channex's own description: "a full sync can be initiated at any time to
// recover from downtimes, errors or other events... Full sync means you
// should send 500 days of Availability, rates and restrictions for all
// rooms and rates on the property." The everyday path here is the AriOutbox
// queue, which only ever covers the range a change actually touched and
// only fires from a change - there was no way to ask for the whole 500-day
// window on demand, which is the exact scenario ("recover from downtimes")
// this test exists to prove. This endpoint is that trigger.
//
// Deliberately bypasses AriOutbox rather than enqueueing 500 days of rows
// for the normal drain cycle to work through: certification asks to
// "attach the returned id(s) generated by our side" as evidence, which
// means the ids have to come back in this response, not surface later in a
// queue that has no user-facing view.
//
//   GET /api/debug/channex-full-sync                    (no propertyId: lists candidates)
//   GET /api/debug/channex-full-sync?propertyId=xxx      (dry run - no Channex call)
//   GET /api/debug/channex-full-sync?propertyId=xxx&apply=true
//
// Chunked rather than one 500-day call, and throttled between chunks at the
// same spacing ari-drain.ts uses for the same reason: Channex's own rate
// limit is account-wide, and this call competes with the drain worker for
// the same budget.

const FULL_SYNC_HORIZON_DAYS = 500; // certification's own number, not the 365 the outbox uses day-to-day
const CHUNK_DAYS = 100; // keeps each payload and each response small enough to inspect
const MIN_MS_BETWEEN_CALLS = 3500; // mirrors ari-drain.ts: 60_000 / 20 calls-per-minute, padded

function addDays(d: Date, n: number): Date {
  const r = new Date(d);
  r.setUTCDate(r.getUTCDate() + n);
  return r;
}

export async function GET(req: NextRequest) {
  const access = await requireDebugAccess(req);
  if (!access.ok) return access.response;

  const { searchParams } = new URL(req.url);
  const propertyId = searchParams.get("propertyId");
  const apply = searchParams.get("apply") === "true";

  if (!propertyId) {
    const properties = await prisma.property.findMany({
      where: { ownerId: access.userId, channelProvider: "CHANNEX" },
      select: { id: true, name: true, channexListing: { select: { channexPropertyId: true } } },
    });
    return NextResponse.json({
      error: "propertyId is required - pick one below and re-run",
      properties: properties.map((p) => ({
        propertyId: p.id,
        name: p.name,
        provisioned: !!p.channexListing,
      })),
    });
  }

  const property = await prisma.property.findFirst({
    where: { id: propertyId, ownerId: access.userId },
    select: { id: true, name: true, channelProvider: true, channexListing: { select: { channexPropertyId: true } } },
  });
  if (!property) return NextResponse.json({ error: "Property not found" }, { status: 404 });
  if (property.channelProvider !== "CHANNEX") {
    return NextResponse.json(
      { error: `${property.name} has channelProvider=${property.channelProvider}, not CHANNEX - nothing to sync` },
      { status: 400 }
    );
  }
  if (!property.channexListing) {
    return NextResponse.json({ error: `${property.name} has no ChannexListing - run /api/channex/provision first` }, { status: 400 });
  }

  const from = new Date();
  from.setUTCHours(0, 0, 0, 0);
  const to = addDays(from, FULL_SYNC_HORIZON_DAYS);

  const chunks: Array<{ from: Date; to: Date }> = [];
  for (let cursor = from; cursor < to; ) {
    const chunkEnd = addDays(cursor, CHUNK_DAYS) < to ? addDays(cursor, CHUNK_DAYS) : to;
    chunks.push({ from: cursor, to: chunkEnd });
    cursor = chunkEnd;
  }

  if (!apply) {
    return NextResponse.json({
      mode: "dry run - no call made to Channex",
      property: property.name,
      horizonDays: FULL_SYNC_HORIZON_DAYS,
      from: from.toISOString().slice(0, 10),
      to: to.toISOString().slice(0, 10),
      plannedCalls: chunks.length,
      hint: "Re-run with &apply=true to actually push. Each call is throttled to stay under Channex's rate limit.",
    });
  }

  const results: Array<{ from: string; to: string; taskIds: string[]; error: string | null }> = [];
  let lastCallAt = 0;

  for (const chunk of chunks) {
    const wait = lastCallAt === 0 ? 0 : MIN_MS_BETWEEN_CALLS - (Date.now() - lastCallAt);
    if (wait > 0) await new Promise((r) => setTimeout(r, wait));
    lastCallAt = Date.now();

    try {
      const taskIds = await pushAriForDateRange(property.id, chunk.from, chunk.to);
      results.push({ from: chunk.from.toISOString().slice(0, 10), to: chunk.to.toISOString().slice(0, 10), taskIds, error: null });
    } catch (err) {
      const e = err as ChannexError;
      results.push({
        from: chunk.from.toISOString().slice(0, 10),
        to: chunk.to.toISOString().slice(0, 10),
        taskIds: [],
        error: `${e.message} (status ${e.status ?? "?"})`,
      });
    }
  }

  const allTaskIds = results.flatMap((r) => r.taskIds);
  const failed = results.filter((r) => r.error);

  return NextResponse.json({
    mode: "applied",
    property: property.name,
    channexPropertyId: property.channexListing.channexPropertyId,
    horizonDays: FULL_SYNC_HORIZON_DAYS,
    from: from.toISOString().slice(0, 10),
    to: to.toISOString().slice(0, 10),
    callsMade: results.length,
    callsFailed: failed.length,
    // What certification asks to see attached as evidence of the sync.
    taskIds: allTaskIds,
    results,
  });
}
